name: pytest

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4   # updated

      - name: Set up Python
        uses: actions/setup-python@v5   # updated
        with:
          python-version: "3.11"   # or your version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pandas sqlalchemy
          pip install allure-pytest
          pip install -r requirements.txt

      - name: Run tests
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_USER: testuser
          DB_PASSWORD: testpass
          DB_NAME: testdb
        run: pytest -v tests/

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4   # updated
        with:
          name: pytest-results
          path: .pytest_cache
