name: ETL Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"   # or 3.10, match your version
      - run: pip install -r requirements.txt
      - run: pytest --html=reports/report.html --self-contained-html
