name: pytest

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4   # updated
      - name: Set up Python
        uses: actions/setup-python@v5   # updated
        with:
          python-version: "3.11"   # or your version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pandas sqlalchemy
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -v

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4   # updated
        with:
          name: pytest-results
          path: .pytest_cache
